apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: api
        image: 773364929699.dkr.ecr.us-east-1.amazonaws.com/api-start-wars-teste
        ports:
        - containerPort: 3000
